### ISSUE TITLE
npm install log.io-ts -g

### ISSUE THREAD

**Issue by johnbritto1** [xialeistudio/log.io-ts#2]
[root](url
[2018-05-29T10_38_20_848Z-debug.log](https://github.com/xialeistudio/log.io-ts/files/2047856/2018-05-29T10_38_20_848Z-debug.log)
)  ~  #  npm install log.io-ts -g
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/xialeistudio/log4js-node.git
npm ERR! 
npm ERR! fatal: cannot come back to cwd: Permission denied
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-29T10_38_20_848Z-debug.log

**Comment by xialeistudio** [comment]
Permission denied

please add `sudo`
